Repository jusleg/simple-calculator-FAMINGO, pull requests merged in 2018-03, with the labels that each got.

#58 Added coding conventions into the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, enhancement

#70 Tipping feature
  app/src/androidTest/java/com/simplemobiletools/calculator/MoneyActivityTest.java
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MoneyActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/MoneyCalculatorImpl.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/operation/TipOperation.kt
  app/src/main/res/layout/tip_dialog.xml
  app/src/test/java/com/simplemobiletools/calculator/MoneyCalculatorImplTest.kt
Labels: User story

#71 Add geolocation on tax button #64 #51
  app/build.gradle
  app/src/androidTest/java/com/simplemobiletools/calculator/MoneyActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MoneyActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/MoneyCalculatorImpl.kt
  app/src/test/java/com/simplemobiletools/calculator/MoneyCalculatorImplTest.kt
  commons/src/main/java/com/simpletools/calculator/commons/operations/TaxOperation.kt
Labels: task

#104 Currency converter implementation [US #42]
  .gitignore
  .travis.yml
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/simplemobiletools/calculator/FakeCurrencyTask.kt
  app/src/androidTest/java/com/simplemobiletools/calculator/MoneyActivityTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MainActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/activities/MoneyActivity.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/BackgroundCurrencyTaskBuilder.java
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/GetCurrencyTask.kt
  app/src/main/kotlin/com/simplemobiletools/calculator/helpers/MoneyCalculatorImpl.kt
  app/src/main/res/layout/conversion_modal.xml
  app/src/main/res/values/strings.xml
  commons/src/main/java/com/simpletools/calculator/commons/helpers/Calculator.kt
  commons/src/test/java/com/simpletools/calculator/commons/FakeCalculatorActivity.kt
Labels: User story, task

#113 Bug fix for wear app #112
  wear/src/main/java/com/simpletools/calculator/wear/MainActivity.kt
Labels: bug
